### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by lebriton** [zaataylor/rich-hn#5]
I maintain an [awesome](https://github.com/topics/awesome) list named [awesome-hackernews](https://github.com/bminusl/awesome-hackernews) where Hacker News related tools are featured.

I noticed `rich-hn` does not have a license. See [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/).

Is this an oversight?

**Comment by zaataylor** [comment]
Hi @bminusl , nice to hear from you! This _is_ an oversight on my part. Honestly, I was so focused on the code that I completely neglected to add a license, but now that you've brought it to my attention, I will add one (it will be MIT) right now.

Thanks for bringing this to my attention! 😄
